const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 40,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      contInStock: 20,
      descrpition: 'A popolar shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 8,
      contInStock: 10,
      descrpition: 'A popolar shirt',
    },
    {
      name: 'SLim Shirt',
      slug: 'slim-shirt',
      category: 'Shirt',
      image: '/images/shirt1.jpg',
      price: 50,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 18,
      contInStock: 14,
      descrpition: 'A popolar shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.9,
      numReviews: 13,
      contInStock: 25,
      descrpition: 'A popolar shirt',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 120,
      brand: 'Zara',
      rating: 4.8,
      numReviews: 13,
      contInStock: 25,
      descrpition: 'A popolar shirt',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 90,
      brand: 'Casely',
      rating: 4.9,
      numReviews: 13,
      contInStock: 25,
      descrpition: 'A popolar shirt',
    },
  ],
};

export default data;
